import type { Metadata } from "next";
import { Mulish as FontSans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Header from "../Header";
import "../globals.css";

const fontSans = FontSans({
   variable: "--font-sans",
   subsets: ["latin"]
});

export const metadata: Metadata = {
   title: {
      template: "%s | SHOBAI",
      default: "SHOBAI"
   },
   description: "Generated by create next app"
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${fontSans.variable} relative h-screen bg-gray-50 font-sans font-medium antialiased`}
         >
            <Toaster />
            {/* <BackgroundGradients /> */}
            <Header />

            <main className="box-container grid size-full h-screen grid-cols-[18rem_1fr_18rem] gap-4 border pt-20">
               <aside className="rounded-xl bg-white p-6">Left Sidebar</aside>

               <main className="rounded-xl bg-white p-6">{children}</main>

               <aside className="rounded-xl bg-white p-6">Right Sidebar</aside>
            </main>
         </body>
      </html>
   );
}
