import type { Metadata } from "next";
import { Mulish as FontSans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import BackgroundGradients from "@/components/ui/gradients";
import Sidebar from "@/components/Sidebar";
import "../globals.css";

const fontSans = FontSans({
   variable: "--font-sans",
   subsets: ["latin"]
});

export const metadata: Metadata = {
   title: {
      template: "%s | SHOBAI",
      default: "SHOBAI"
   },
   description: "Generated by create next app"
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${fontSans.variable} relative max-h-screen font-sans font-medium antialiased`}
         >
            <Toaster />
            <BackgroundGradients />

            <main className="relative flex h-screen w-screen flex-col overflow-y-auto">
               <section className="grid flex-1 grid-cols-[20rem_1fr]">
                  <Sidebar />

                  <section className="col-span-1 col-start-2 h-screen overflow-hidden p-3">
                     <main className="shadow-card lex scroll-hide relative h-full flex-col space-y-6 overflow-y-auto rounded-lg bg-white p-3 text-justify">
                        {children}
                     </main>
                  </section>
               </section>
            </main>
         </body>
      </html>
   );
}
