import type { Metadata } from "next";
import { Mulish as FontSans } from "next/font/google";
import { ReactLenis } from "@/lib/lenis";
import "../globals.css";

const fontSans = FontSans({
   variable: "--font-sans",
   subsets: ["latin"]
});

export const metadata: Metadata = {
   title: {
      template: "%s | SHOBAI",
      default: "SHOBAI"
   },
   description: "Generated by create next app"
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <ReactLenis root>
         <html lang="en">
            <body
               className={`${fontSans.variable} relative flex h-screen items-center justify-center font-sans antialiased`}
            >
               {children}
            </body>
         </html>
      </ReactLenis>
   );
}
