import type { Metadata } from "next";
import { Mulish as FontSans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Header from "../Header";
import "../globals.css";

const fontSans = FontSans({
   variable: "--font-sans",
   subsets: ["latin"]
});

export const metadata: Metadata = {
   title: {
      template: "%s | SHOBAI",
      default: "SHOBAI"
   },
   description: "Generated by create next app"
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${fontSans.variable} relative h-screen bg-gray-50 font-sans font-medium antialiased`}
         >
            <Toaster />
            <Header />

            <main className="box-container size-full h-screen pt-20">{children}</main>
         </body>
      </html>
   );
}
