import type { Metadata } from "next";
import { Mulish as FontSans } from "next/font/google";
import { AuthSessionProvider } from "@/context/session";
import { QueryClientProvider } from "@/context/react-query";
import { Toaster } from "react-hot-toast";
import Header from "@/components/Header";
import "../globals.css";

const fontSans = FontSans({
   variable: "--font-sans",
   subsets: ["latin"]
});

export const metadata: Metadata = {
   title: {
      template: "%s | SHOBAI",
      default: "SHOBAI"
   },
   description: "Generated by create next app"
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <AuthSessionProvider>
         <QueryClientProvider>
            <html lang="en">
               <body
                  className={`${fontSans.variable} relative h-screen overflow-hidden bg-white font-sans font-medium antialiased`}
               >
                  <Toaster />
                  <Header />
                  {children}
               </body>
            </html>
         </QueryClientProvider>
      </AuthSessionProvider>
   );
}
